services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'senior_meet_db'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  spring-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
